name: Build-Publish

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Name of image to build and deploy'
        required: true
        type: string

env:
  registry: ghcr.io/netwarlan
  branch: ${{ github.head_ref || github.ref_name }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Branch Tagging
        if: ${{ env.branch == 'main' }}
        run: |
          echo "branch=latest" >> $GITHUB_ENV

      - name: Build and Publish Image
        run: |
          docker build . --tag ${{ env.registry }}/${{ inputs.image-name }}:${{ env.branch }}
          docker push ${{ env.registry }}/${{ inputs.image-name }}:${{ env.branch }}